name: Main CI

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  Build_and_Release:
    name: Build & Release & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: set vars
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
      - name: restore node cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: build frontend
        run: make vue
      - name: setup go env
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: restore Go mod cache
        uses: actions/cache@v2
        with:
         path: ~/go/pkg/mod
         key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
         restore-keys: |
           ${{ runner.os }}-go-
      - name: build app dist
        run: |
          make prin
      - name: release prin
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: aaronzjc/prin
          tags: latest, ${{ steps.vars.outputs.sha_short }}
      - name: setup ktl
        uses: azure/setup-kubectl@v1
        id: install
      - name: deploy
        run: |
          cat << EOF > kube-config
          ${{ secrets.KUBECONF }}
          EOF
          export KUBECONFIG=$(pwd)/kube-config
          curl -o prin.yml https://raw.githubusercontent.com/aaronzjc/k3s/main/Deployment/prin.yml
          sed -i ""s/latest/${{ steps.vars.outputs.sha_short }}/g" prin.yml
          car prin.yml
          kubectl rollout restart -f prin.yml -n k3s-apps
